name: Generate Stats
on:
  schedule: [{cron: "0 0 * * *"}] # Runs daily
  workflow_dispatch: # Allows manual trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate stats card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: stats
          options: 'username=${{ github.repository_owner }}&show_icons=true&theme=tokyonight'
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate languages card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: top-langs
          options: 'username=${{ github.repository_owner }}&layout=compact&theme=tokyonight'
          path: profile/langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
